### ISSUE TITLE
Adjust scrollbar to dark theme

### ISSUE THREAD

**Issue by thiagobraga** [thiagobraga/google-calendar-userstyles#5]
The scroll bar looks pretty ugly in the dark theme. Try customizing the scroll bar to suit the One Dark theme.

![image](https://user-images.githubusercontent.com/993684/65272147-f2174f00-daf4-11e9-8f16-86e8e8b22759.png)

**Comment by metruzanca** [comment]
I would have made a PR but i don't know how this is done in stylus, but this looks pretty nice imho.
```css
* {
    scrollbar-color: #31343f #1e2127;
}
````
![firefox_CrRth1RNTi](https://user-images.githubusercontent.com/32832892/69533730-a8c20080-0f78-11ea-9527-143b8590992d.png)

**Comment by thiagobraga** [comment]
Thanks, friend @metruzanca. Thanks for share your idea, and sorry for the delay.
I solved the problem in this commit [369c0691](https://github.com/thiagobraga/google-calendar-userstyles/commit/369c091dfbe0043c444a99f0ae5331ef72182dec), if you want to take a look :relaxed: 
It worked well on Chrome and Firefox.

![Captura de tela de 2020-08-09 15-11-13](https://user-images.githubusercontent.com/993684/89740164-cda1c980-da5c-11ea-9452-b244505a118c.png)

![Captura de tela de 2020-08-09 15-17-17](https://user-images.githubusercontent.com/993684/89740215-2d987000-da5d-11ea-846e-9ae6a7bd6603.png)

![Captura de tela de 2020-08-09 15-11-59](https://user-images.githubusercontent.com/993684/89740217-32f5ba80-da5d-11ea-969e-39d52781ccfb.png)
